### ISSUE TITLE
readme updates

### ISSUE THREAD

**Issue by gkulin** [Arize-ai/phoenix-on-azure#3]
remove 
- pip install
- azd env new

add
- turn on resource group scoped deployments (`azd config set alpha.resourceGroupDeployments on`)

When I was running `azd provision` I was prompted for 
```
- Enter a value for the 'databasePassword' infrastructure secured parameter
- Enter a value for the 'htpasswd' infrastructure parameter
```
is this what we want? If so we should mention them in the readme

**Comment by gkulin** [comment]
@kristenwomack and I are happy to work on this!

**Comment by kristenwomack** [comment]
> @kristenwomack and I are happy to work on this!

@loopingz - assign us if this is a change you want done and we'll pick it up.

**Comment by loopingz** [comment]
No, in the original version the htpasswd is generated dynamically as the database password by the `init.py` script

**Comment by loopingz** [comment]
@gkulin can you now close this issue based on your merged PR? Thank you both @kristenwomack and @gkulin for your work on this

**Comment by kristenwomack** [comment]
> No, in the original version the htpasswd is generated dynamically as the database password by the `init.py` script

One more question on this -- when prompted for the passwords, I enter nothing and select enter -- is this correct? It's what I do with my deployment and it works. If this is correct for the dynamic PW generation, then I will submit a separate PR with those changes to the README to so folks know what to do. 

![image](https://github.com/Arize-ai/phoenix-on-azure/assets/5034778/87390784-21f5-4e4b-9e13-d0bf57420520)

**Comment by loopingz** [comment]
Normally it does not prompt you for these, maybe something has changed, I need to test it on my side to confirm you.

**Comment by kristenwomack** [comment]
Thank you and let me know!

**Comment by loopingz** [comment]
The issue came from the command `azd up` this command is not triggering the provision hooks.

I updated the README to replace `azd up` by
```
azd config set alpha.resourceGroupDeployments on
# azd env set PERSISTENCE true
azd provision
```

**Comment by loopingz** [comment]
@kristenwomack can you confirm it works for you this way now so I can close this issue?

**Comment by kristenwomack** [comment]
Hi @loopingz - I'm able to do a successful deployment on [this branch](https://github.com/Arize-ai/phoenix-on-azure/tree/fix/pr-5) using the resource group deployments feature `azd config set alpha.resourceGroupDeployments on` and I am still getting prompted to set these credentials, where I select `enter` 2x to continue. I am not able to deploy from `main`.

![image](https://github.com/Arize-ai/phoenix-on-azure/assets/5034778/45913c51-abe2-4b0f-aeea-485d2486f322)

**Comment by kristenwomack** [comment]
@loopingz - we confirmed that @gkulin can deploy from `main`. You can close this issue, and I'll keep testing and troubleshoot my errors. However, I do think we should add a note in the README about what to do when prompted for the values for `databasePassword` and `htpasswd`. Both @gkulin and I are consistently prompted for these. We push `enter` with an empty value to proceed. Having a note would help clarify any potential confusion.

**Comment by loopingz** [comment]
Closing this one now as #10 did solve the issue, thank you so much for your talk yesterday and your overall guidance.
